#server:
#  port: 8000
#spring:
#  application:
#    name: spring-cloud-ali-goods
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.139.129:8848
#        username: nacos
#        password: nacos