#server:
#  port: 8020
#spring:
#  application:
#    name: spring-cloud-ali-shopcart
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.139.129:8848
#        username: nacos
#        password: nacos
#        register-enabled: false
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: 192.168.139.129:8858
#dynamic:
#  config:
#    user-name: lixianch11
#feign:
#  sentinel:
#    enabled: true